# -*- coding: utf-8 -*-
"""Cat_Dog classifier using transfer learning(data-augmentation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lu4WB_aVnxE5I8GbR-PBuMG_Q9dGFSrK
"""

!kaggle datasets download shaunthesheep/microsoft-catsvsdogs-dataset

import zipfile
zip_ref = zipfile.ZipFile('/content/microsoft-catsvsdogs-dataset.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Flatten
from keras.applications.vgg16 import VGG16

import os
import tensorflow as tf

data_dir = '/content/PetImages'
removed_count = 0

# Scan all files using TensorFlow's own strict decoder
for root, dirs, files in os.walk(data_dir):
    for file in files:
        file_path = os.path.join(root, file)

        # Skip hidden files
        if file.startswith('.'):
            continue

        try:
            # 1. Read the raw file bytes
            raw_img = tf.io.read_file(file_path)
            # 2. Force TensorFlow to decode it as a JPEG/PNG image
            tf.io.decode_image(raw_img, channels=3, expand_animations=False)
        except tf.errors.InvalidArgumentError:
            # If TensorFlow crashes trying to read it, delete it
            print(f"TensorFlow rejected and removed: {file_path}")
            os.remove(file_path)
            removed_count += 1

print(f"Cleanup finished. Total bad images removed by TensorFlow: {removed_count}")

import tensorflow as tf

data_dir = '/content/PetImages'
batch_size = 32
train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(150, 150),
    batch_size=batch_size
)

validation_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(150, 150),
    batch_size=batch_size
)

from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2),
])

train_ds = train_ds.map(lambda x, y: (data_augmentation(x, training=True), y))
train_ds = train_ds.map(lambda x, y: (x / 255.0, y))

validation_ds = validation_ds.map(lambda x, y: (x / 255.0, y))

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
validation_ds = validation_ds.cache().prefetch(buffer_size=AUTOTUNE)

conv_base = VGG16(
    weights='imagenet',
    include_top = False,
    input_shape=(150,150,3)
)

from keras.layers import Dropout
model = Sequential()

model.add(conv_base)
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.35))
model.add(Dense(1,activation='sigmoid'))

conv_base.trainable = False

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

from keras.callbacks import EarlyStopping
early_stop=EarlyStopping(monitor='val_loss',patience=2,restore_best_weights=True)

history = model.fit(
        train_ds,
        epochs=10,
        validation_data=validation_ds,callbacks=[early_stop])

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

plt.plot(history.history['loss'],color='red',label='train')
plt.plot(history.history['val_loss'],color='blue',label='validation')
plt.legend()
plt.show()

import numpy as np

img = tf.keras.utils.load_img('/content/cat.jpg', target_size=(150, 150))
img_array = tf.keras.utils.img_to_array(img)

img_array = tf.expand_dims(img_array, 0)
img_array = img_array / 255.0

prediction=model.predict(img_array)


import matplotlib.pyplot as plt
plt.imshow(img)
plt.axis('off')
plt.show()

if prediction[0][0]>0.5:
   confidence=(prediction[0][0])*100
   print('Dog')
   print("Confidence=",confidence)
else:
   confidence=(1-prediction[0][0])*100
   print('Cat')
   print("Confidence=",confidence)